### ISSUE TITLE
Running test with all steps skipped causes error with cy.wait() outside of it() block

### ISSUE THREAD

**Issue by wintrell523** [archfz/cypress-terminal-report#116]
Hello. I ran into a problem - I have a test, which needs to be skipped because of bugs present in the app.
What I did is mark all it() blocks with .skip.
When I run the test in CLI following error appears:
``` 
Running:  businessCase/TQA-569-BC-Buying-OnStock-UndeductibleVehicle-Cash.ts             (5 of 16)
  TQA-569: BC Buying | On Stock | Undeductible Vehicle | Cash
    - Step 1 - List
    - Step 2 - Create customer
    1) "before all" hook in "TQA-569: BC Buying | On Stock | Undeductible Vehicle | Cash"
  0 passing (750ms)
  2 pending
  1 failing
  1) TQA-569: BC Buying | On Stock | Undeductible Vehicle | Cash
       "before all" hook in "TQA-569: BC Buying | On Stock | Undeductible Vehicle | Cash":
     CypressError: Cannot call `cy.wait()` outside a running test.
This usually happens when you accidentally write commands outside an `it(...)` test.
If that is the case, just move these commands inside an `it(...)` test.
Check your test file for errors.
Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `TQA-569: BC Buying | On Sto...`
      at Object.ensureRunnable (http://localhost:3000/__cypress/runner/cypress_runner.js:143964:24)
      at $Cy.cy.<computed> [as wait] (http://localhost:3000/__cypress/runner/cypress_runner.js:153381:17)
      at Runner.emit (http://localhost:3000/__cypress/runner/cypress_runner.js:19033:7)
      at next (http://localhost:3000/__cypress/runner/cypress_runner.js:110124:14)
      at next (http://localhost:3000/__cypress/runner/cypress_runner.js:110127:14)
      at next (http://localhost:3000/__cypress/runner/cypress_runner.js:110127:14)
      at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTests (http://localhost:3000/__cypress/runner/cypress_runner.js:110197:3)
      at Runner.runTests (http://localhost:3000/__cypress/runner/cypress_runner.js:157809:32)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:110277:10
      at next (http://localhost:3000/__cypress/runner/cypress_runner.js:109850:14)
      at Hook.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:109911:7)
      at next (http://localhost:3000/__cypress/runner/cypress_runner.js:159559:22)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:159586:11
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:10798:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:8733:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:8790:18)
```

Problem is I don't have any `cy.wait()` outside of `it()` block. When I disable the plugin, everything runs OK and this test is marked as skipped.

I tried to remove the `.skip` at `it()` block level and move it to `describe()` block instead. When I run that, the test hangs and doesn't run at all. Again, works OK when the plugin is disabled.

Cypress: 8.0.0
Node: 14.15.1 (bundled)
cypress-terminal-report: 3.3.0

I had the plugin set to default, no custom config (so to 'onFail').

**Comment by archfz** [comment]
Released in 3.3.1
