### ISSUE TITLE
Plugin fails on Cannot find module 'cypress-terminal-report/src/installLogsPrinter' in Github Actions

### ISSUE THREAD

**Issue by Garajluc** [archfz/cypress-terminal-report#181]
Hello,
following the plugin implementation based on [documentation](https://github.com/archfz/cypress-terminal-report#readme) we have faced two type of Errors: 
  - in case we used `cypress.config.ts`, the github action job 'cypress run' failed on `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /cypress.config.ts`
  - when we changed the extension to `.js` e.g. `cypress.config.js` (together with the type of import statements and so on), we have faced following error: `Error: Cannot find module 'cypress-terminal-report/src/installLogsPrinter'`. See the [pipeline job](https://github.com/assetario/console/actions/runs/4480515625/jobs/7876612912)
  
  Full error log: 
```
  Your configFile is invalid: /cypress.config.js

It threw an error when required, check the stack trace below:

Error: Cannot find module 'cypress-terminal-report/src/installLogsPrinter'
Require stack:
- /cypress.config.js
- /root/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js
- /root/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/cypress.config.js:2:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:8[22](https://github.com/assetario/console/actions/runs/4480515625/jobs/7876612912#step:19:23):12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (/root/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/root/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:5[26](https://github.com/assetario/console/actions/runs/4480515625/jobs/7876612912#step:19:27):[28](https://github.com/assetario/console/actions/runs/4480515625/jobs/7876612912#step:19:29))
    at process.<anonymous> (/root/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:[33](https://github.com/assetario/console/actions/runs/4480515625/jobs/7876612912#step:19:34):22)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:9[38](https://github.com/assetario/console/actions/runs/4480515625/jobs/7876612912#step:19:39):14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```
    
  
** the plugin works locally without any issues. 

Thank you for the plugin and you support :)

**Comment by archfz** [comment]
Closing due to lack of activity. Please feel free to add more details and will reopen.
