### ISSUE TITLE
Cypress not found error

### ISSUE THREAD

**Issue by igorgiumellizup** [archfz/cypress-terminal-report#204]
Dependencies:
```json
  "devDependencies": {
    "cypress": "^12.15.0",
    "cypress-split": "^1.3.15",
    "cypress-terminal-report": "^5.3.2",
    "cypress-wait-for-stable-dom": "^0.1.0"
  }
```

Snippet of `cypress.config.js`

```js

    setupNodeEvents(on, config) {

      // allows information printed in CI / Terminal by calling cy.task('log', ...anyDebugDataHere)
      on('task', {
        log: message => {
          console.log(message);
          return null;
        },
      });

      // cypress-terminal-report
      const logPrinterOptions = {
        printLogsToConsole: 'always'
      }
      const logCollectorOptions = {
        // Logs browser's console output only
        collectTypes: ["cons:log", "cons:info", "cons:warn", "cons:error"]
      };
      require('cypress-terminal-report/src/installLogsPrinter')(on, logPrinterOptions);
      require('cypress-terminal-report/src/installLogsCollector')(logCollectorOptions)

      // cypress-split
      cypressSplit(on, config)
      return config
    },
```

Snippet of e2e.js
```js
// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')

require('cypress-terminal-report/src/installLogsCollector')();
require('cypress-terminal-report/src/installLogsPrinter')();

Cypress.on('uncaught:exception', (err, runnable) => {
    console.log("Warning: exception " + err.message)
    return false
})
```

When running tests I get
Error:

```
ReferenceError: Cypress is not defined
    at LogCollectBrowserConsole.register (/Users/igordgzup/workspaces/stackspot/portal-automated-tests/node_modules/cypress-terminal-report/src/collector/LogCollectBrowserConsole.js:15:5)
    at registerLogCollectorTypes (/Users/igordgzup/workspaces/stackspot/portal-automated-tests/node_modules/cypress-terminal-report/src/installLogsCollector.js:49:61)
    at installLogsCollector (/Users/igordgzup/workspaces/stackspot/portal-automated-tests/node_modules/cypress-terminal-report/src/installLogsCollector.js:37:3)
    at setupNodeEvents (/Users/igordgzup/workspaces/stackspot/portal-automated-tests/cypress.config.js:32:66)
    at /Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:122:14
    at tryCatcher (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at RunPlugins.load (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:119:9)
    at RunPlugins.runSetupNodeEvents (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:59:17)
    at EventEmitter.<anonymous> (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:185:22)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)
    at process.<anonymous> (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:526:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/igordgzup/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

Any help?

**Comment by igorgiumellizup** [comment]
Actually this part

```js
const logCollectorOptions = {
    // Logs browser's console output only
    collectTypes: ["cons:log", "cons:info", "cons:warn", "cons:error"]
  };
require('cypress-terminal-report/src/installLogsCollector')(logCollectorOptions)
```

is supposed to be in e2e.js

Closing issue
