### ISSUE TITLE
Getting error in component testing

### ISSUE THREAD

**Issue by piotrpalek** [archfz/cypress-terminal-report#225]
I have Cypress 13.5.1 and I'm using it with Vite 5.0.2

I'm getting this error when running Cypress via `cypress run` (doesn't happen when I run it via the GUI):

```
  1) <RecentActivityCard />
       "before each" hook for "Renders locked state":
     TypeError: Cannot destructure property 'args' of 'Cypress.emitMap(...)[0]' as it is undefined.

Because this error occurred during a `before each` hook we are skipping all of the remaining tests.
      at Object.nonQueueTask (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:4288:19)
      at LogCollectSimpleControl.sendLogsToPrinter (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:5350:17)
      at <unknown> (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:5399:18)
      at <unknown> (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:4943:61)
      at Array.forEach (<anonymous>)
      at LogCollectorState.emit (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:4943:39)
      at LogCollectorState.addLog (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:4861:14)
      at Context.<anonymous> (http://localhost:3050/__cypress/src/node_modules/.vite/deps/cypress-terminal-report_src_installLogsCollector.js?v=c573dfcd:4790:31)
      at overridden.fn (http://localhost:3050/__cypress/runner/cypress_runner.js:111038:21)
      at wrapped (http://localhost:3050/__cypress/runner/cypress_runner.js:138644:43)
```

I'll try to investigate more, but for now this is all I have.
Initially I didn't even see this error, it looked like it was just hanging there with no output,  I tried various options and I think the combinations of `printLogsToConsole: 'always',` and `enableContinuousLogging: true` allowed me to see the issue.

edit: opened the relevant file from the stacktrace in the browser, maybe this'll help a bit:

<img width="943" alt="image" src="https://github.com/archfz/cypress-terminal-report/assets/1474323/be1af507-dd90-4231-b0f5-414375f8c991">

**Comment by archfz** [comment]
They might have introduced a breaking change.

**Comment by bvandercar-vt** [comment]
+1

**Comment by archfz** [comment]
Forgot to mention that i did a release for this. In 5.3.10. Please check.
